openapi: 3.0.3
info:
  title: Simple Weather
  description: |-
    The project involves the development of a Ruby on Rails application that serves as an API for retrieving weather data based on city input, coordinates or ip params.<br>
    Additionally implemented features:
    1) Basic token authentication system;
    2) Scheduling weather forecasts delivery by email;<br><br>

    Project utilizes [public weather API](https://www.weatherapi.com/docs/).<br><br>
    The application is designed with scalability in mind, paving the way for potential future enhancements.

  contact:
    email: alex.hrynts@gmail.com
  version: 0.1.0
tags:
  - name: API Keys
    description: API Keys for authentication
  - name: Weather
    description: Retrieve or schedule weather forecast
paths:
  /api/v1/api_keys:
    post:
      tags:
        - API Keys
      summary: Generate API Key for authentication
      description: Creates new API key with Default Subscription Plan
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiKey'
  /api/v1/weather:
    get:
      tags:
        - Weather
      summary: Retrieve weather forecast
      description: Query weather forecast from thrid-party API service. Use city or lat, lon or ip. Usign both variants causes error response
      parameters:
        - name: key
          in: query
          description: API key with sufficient Subscription Plan permissions
          required: true
          schema:
            type: string
        - name: city
          in: query
          description: 'City for desired forecast'
          required: false
          schema:
            type: string
        - name: lat
          in: query
          description: 'Latitude'
          required: false
          schema:
            type: number
        - name: lon
          in: query
          description: 'Longitude'
          required: false
          schema:
            type: number
        - name: ip
          in: query
          description: 'IP'
          required: false
          schema:
            type: string
        - name: days
          in: query
          description: 'Days from now for forecasts'
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DaysArray'
        '400':
          description: Invalid params supplied
          content:
            application/json:
              schema:
                type: object
                example:
                  - errors:
                    - 'Service is temporarily unavailable'
                  - errors:
                    - 'Days not in range of applied subscription plan'
                  - errors:
                    - 'Please provide correct query params'
        '401':
          description: Invalid API key
          content:
            application/json:
              schema:
                type: object
                example:
                  - error: 'API key is missing or invalid'
        '403':
          description: Insufficient privileges to access the resource
          content:
            application/json:
              schema:
                type: object
                example:
                  - error: 'You do not have permission to access this resource.'
  /api/v1/weather/schedule:
    post:
      tags:
        - Weather
      summary: Configure schedule to receive weather forecasts
      description: Configure schedule to receive weather forecasts. Weekdays, time, email and key params are mandatory and you have to choose one from city, lat/lon or ip.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                key:
                  type: string
                  example: 9fc20309cfef440caa51c56d3c7da836
                time:
                  type: string
                  example: '11:00'
                weekdays:
                  type: string
                  example: 'MO,WE,SU'
                email:
                  type: string
                  example: 'alex.hrynts@gmail.com'
                city:
                  type: string
                  example: 'London'
                lat:
                  type: number
                  example: 55.01
                lon:
                  type: number
                  example: 44.12
                ip:
                  type: string
                  example: '192.168.0.1'
                days:
                  type: integer
                  example: 3
      responses:
        '200':
          description: Mail service was successfully scheduled
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Weather mailing service was scheduled successfully. Schedule: Weekly on Sundays, Mondays, and Tuesdays on the 11th hour of the day on the 0th minute of the hour'
                    
        '400':
          description: Invalid params supplied
          content:
            application/json:
              schema:
                type: object
                example:
                  - errors:
                    - 'Service is temporarily unavailable'
                  - errors:
                    - 'Days not in range of applied subscription plan'
                  - errors:
                    - 'Please provide correct query params'
        '401':
          description: Invalid API key
          content:
            application/json:
              schema:
                type: object
                example:
                  - error: 'API key is missing or invalid'
        '403':
          description: Insufficient privileges to access the resource
          content:
            application/json:
              schema:
                type: object
                example:
                  - error: 'You do not have permission to access this resource.'            
                      
components:
  schemas:
    apiKey:
      x-hidden: true
      type: object
      properties:
        value:
          type: string
          description: SecureRandom UUID
          example: 9fc20309cfef440caa51c56d3c7da836
    Day:
      x-hidden: true
      type: object
      properties:
        date:
          type: string
        avgtemp_c:
          type: number
        maxwind_kph:
          type: number
        totalprecip_mm:
          type: number
        totalsnow_cm:
          type: number
        daily_chance_of_rain:
          type: number
        daily_chance_of_snow:
          type: number
    DaysArray:
      x-hidden: true
      type: array
      items:
        $ref: '#/components/schemas/Day'
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: query
