default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", 'localhost') %>
  database: <%= ENV.fetch('DB', 'sweather_prod') %>
  username: <%= ENV.fetch('POSTGRES_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'postgres') %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
